// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frostEvent.proto

package com.palmap.rssi.message;

public final class FrostEvent {
  private FrostEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.palmap.rssi.message.IdType}
   */
  public enum IdType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MAC = 0;</code>
     */
    MAC(0, 0),
    /**
     * <code>UUID = 1;</code>
     */
    UUID(1, 1),
    /**
     * <code>UNKNOWN_TYPE = 2;</code>
     */
    UNKNOWN_TYPE(2, 2),
    ;

    /**
     * <code>MAC = 0;</code>
     */
    public static final int MAC_VALUE = 0;
    /**
     * <code>UUID = 1;</code>
     */
    public static final int UUID_VALUE = 1;
    /**
     * <code>UNKNOWN_TYPE = 2;</code>
     */
    public static final int UNKNOWN_TYPE_VALUE = 2;


    public final int getNumber() { return value; }

    public static IdType valueOf(int value) {
      switch (value) {
        case 0: return MAC;
        case 1: return UUID;
        case 2: return UNKNOWN_TYPE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<IdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<IdType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<IdType>() {
            public IdType findValueByNumber(int number) {
              return IdType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return FrostEvent.getDescriptor().getEnumTypes().get(0);
    }

    private static final IdType[] VALUES = values();

    public static IdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private IdType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.palmap.rssi.message.IdType)
  }

  /**
   * Protobuf enum {@code com.palmap.rssi.message.StubType}
   */
  public enum StubType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AP = 0;</code>
     */
    AP(0, 0),
    /**
     * <code>BLUETOOTH = 1;</code>
     */
    BLUETOOTH(1, 1),
    /**
     * <code>UNKNOWN_STUB_TYPE = 2;</code>
     */
    UNKNOWN_STUB_TYPE(2, 2),
    ;

    /**
     * <code>AP = 0;</code>
     */
    public static final int AP_VALUE = 0;
    /**
     * <code>BLUETOOTH = 1;</code>
     */
    public static final int BLUETOOTH_VALUE = 1;
    /**
     * <code>UNKNOWN_STUB_TYPE = 2;</code>
     */
    public static final int UNKNOWN_STUB_TYPE_VALUE = 2;


    public final int getNumber() { return value; }

    public static StubType valueOf(int value) {
      switch (value) {
        case 0: return AP;
        case 1: return BLUETOOTH;
        case 2: return UNKNOWN_STUB_TYPE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StubType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<StubType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StubType>() {
            public StubType findValueByNumber(int number) {
              return StubType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return FrostEvent.getDescriptor().getEnumTypes().get(1);
    }

    private static final StubType[] VALUES = values();

    public static StubType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private StubType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.palmap.rssi.message.StubType)
  }

  public interface RssiItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id_data = 1;
    /**
     * <code>required string id_data = 1;</code>
     */
    boolean hasIdData();
    /**
     * <code>required string id_data = 1;</code>
     */
    String getIdData();
    /**
     * <code>required string id_data = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdDataBytes();

    // required .com.palmap.rssi.message.IdType id_type = 2;
    /**
     * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
     */
    boolean hasIdType();
    /**
     * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
     */
    IdType getIdType();

    // required int32 rssi = 3;
    /**
     * <code>required int32 rssi = 3;</code>
     */
    boolean hasRssi();
    /**
     * <code>required int32 rssi = 3;</code>
     */
    int getRssi();
  }
  /**
   * Protobuf type {@code com.palmap.rssi.message.RssiItem}
   */
  public static final class RssiItem extends
      com.google.protobuf.GeneratedMessage
      implements RssiItemOrBuilder {
    // Use RssiItem.newBuilder() to construct.
    private RssiItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RssiItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RssiItem defaultInstance;
    public static RssiItem getDefaultInstance() {
      return defaultInstance;
    }

    public RssiItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RssiItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              idData_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              IdType value = IdType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                idType_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rssi_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FrostEvent.internal_static_com_palmap_rssi_message_RssiItem_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FrostEvent.internal_static_com_palmap_rssi_message_RssiItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RssiItem.class, Builder.class);
    }

    public static com.google.protobuf.Parser<RssiItem> PARSER =
        new com.google.protobuf.AbstractParser<RssiItem>() {
      public RssiItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RssiItem(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RssiItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id_data = 1;
    public static final int ID_DATA_FIELD_NUMBER = 1;
    private Object idData_;
    /**
     * <code>required string id_data = 1;</code>
     */
    public boolean hasIdData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id_data = 1;</code>
     */
    public String getIdData() {
      Object ref = idData_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          idData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id_data = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdDataBytes() {
      Object ref = idData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        idData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .com.palmap.rssi.message.IdType id_type = 2;
    public static final int ID_TYPE_FIELD_NUMBER = 2;
    private IdType idType_;
    /**
     * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
     */
    public boolean hasIdType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
     */
    public IdType getIdType() {
      return idType_;
    }

    // required int32 rssi = 3;
    public static final int RSSI_FIELD_NUMBER = 3;
    private int rssi_;
    /**
     * <code>required int32 rssi = 3;</code>
     */
    public boolean hasRssi() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 rssi = 3;</code>
     */
    public int getRssi() {
      return rssi_;
    }

    private void initFields() {
      idData_ = "";
      idType_ = IdType.MAC;
      rssi_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIdData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRssi()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdDataBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, idType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, rssi_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdDataBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, idType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rssi_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RssiItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RssiItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RssiItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RssiItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RssiItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RssiItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RssiItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RssiItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RssiItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RssiItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RssiItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.palmap.rssi.message.RssiItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RssiItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FrostEvent.internal_static_com_palmap_rssi_message_RssiItem_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FrostEvent.internal_static_com_palmap_rssi_message_RssiItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RssiItem.class, Builder.class);
      }

      // Construct using com.palmap.rssi.message.FrostEvent.RssiItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        idData_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        idType_ = IdType.MAC;
        bitField0_ = (bitField0_ & ~0x00000002);
        rssi_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FrostEvent.internal_static_com_palmap_rssi_message_RssiItem_descriptor;
      }

      public RssiItem getDefaultInstanceForType() {
        return RssiItem.getDefaultInstance();
      }

      public RssiItem build() {
        RssiItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RssiItem buildPartial() {
        RssiItem result = new RssiItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.idData_ = idData_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.idType_ = idType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rssi_ = rssi_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RssiItem) {
          return mergeFrom((RssiItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RssiItem other) {
        if (other == RssiItem.getDefaultInstance()) return this;
        if (other.hasIdData()) {
          bitField0_ |= 0x00000001;
          idData_ = other.idData_;
          onChanged();
        }
        if (other.hasIdType()) {
          setIdType(other.getIdType());
        }
        if (other.hasRssi()) {
          setRssi(other.getRssi());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIdData()) {
          
          return false;
        }
        if (!hasIdType()) {
          
          return false;
        }
        if (!hasRssi()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RssiItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RssiItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id_data = 1;
      private Object idData_ = "";
      /**
       * <code>required string id_data = 1;</code>
       */
      public boolean hasIdData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id_data = 1;</code>
       */
      public String getIdData() {
        Object ref = idData_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          idData_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string id_data = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdDataBytes() {
        Object ref = idData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          idData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id_data = 1;</code>
       */
      public Builder setIdData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        idData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id_data = 1;</code>
       */
      public Builder clearIdData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        idData_ = getDefaultInstance().getIdData();
        onChanged();
        return this;
      }
      /**
       * <code>required string id_data = 1;</code>
       */
      public Builder setIdDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        idData_ = value;
        onChanged();
        return this;
      }

      // required .com.palmap.rssi.message.IdType id_type = 2;
      private IdType idType_ = IdType.MAC;
      /**
       * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
       */
      public boolean hasIdType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
       */
      public IdType getIdType() {
        return idType_;
      }
      /**
       * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
       */
      public Builder setIdType(IdType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        idType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
       */
      public Builder clearIdType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        idType_ = IdType.MAC;
        onChanged();
        return this;
      }

      // required int32 rssi = 3;
      private int rssi_ ;
      /**
       * <code>required int32 rssi = 3;</code>
       */
      public boolean hasRssi() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 rssi = 3;</code>
       */
      public int getRssi() {
        return rssi_;
      }
      /**
       * <code>required int32 rssi = 3;</code>
       */
      public Builder setRssi(int value) {
        bitField0_ |= 0x00000004;
        rssi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rssi = 3;</code>
       */
      public Builder clearRssi() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rssi_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.palmap.rssi.message.RssiItem)
    }

    static {
      defaultInstance = new RssiItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.palmap.rssi.message.RssiItem)
  }

  public interface RssiInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id_data = 1;
    /**
     * <code>required string id_data = 1;</code>
     */
    boolean hasIdData();
    /**
     * <code>required string id_data = 1;</code>
     */
    String getIdData();
    /**
     * <code>required string id_data = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdDataBytes();

    // required .com.palmap.rssi.message.IdType id_type = 2;
    /**
     * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
     */
    boolean hasIdType();
    /**
     * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
     */
    IdType getIdType();

    // required .com.palmap.rssi.message.StubType stub_type = 3;
    /**
     * <code>required .com.palmap.rssi.message.StubType stub_type = 3;</code>
     */
    boolean hasStubType();
    /**
     * <code>required .com.palmap.rssi.message.StubType stub_type = 3;</code>
     */
    StubType getStubType();

    // required int64 timestamp = 4;
    /**
     * <code>required int64 timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 4;</code>
     */
    long getTimestamp();

    // repeated .com.palmap.rssi.message.RssiItem items = 5;
    /**
     * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
     */
    java.util.List<RssiItem>
        getItemsList();
    /**
     * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
     */
    RssiItem getItems(int index);
    /**
     * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
     */
    java.util.List<? extends RssiItemOrBuilder>
        getItemsOrBuilderList();
    /**
     * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
     */
    RssiItemOrBuilder getItemsOrBuilder(
            int index);

    // required int64 scene_id = 6;
    /**
     * <code>required int64 scene_id = 6;</code>
     */
    boolean hasSceneId();
    /**
     * <code>required int64 scene_id = 6;</code>
     */
    long getSceneId();
  }
  /**
   * Protobuf type {@code com.palmap.rssi.message.RssiInfo}
   */
  public static final class RssiInfo extends
      com.google.protobuf.GeneratedMessage
      implements RssiInfoOrBuilder {
    // Use RssiInfo.newBuilder() to construct.
    private RssiInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RssiInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RssiInfo defaultInstance;
    public static RssiInfo getDefaultInstance() {
      return defaultInstance;
    }

    public RssiInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RssiInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              idData_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              IdType value = IdType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                idType_ = value;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              StubType value = StubType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                stubType_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readInt64();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                items_ = new java.util.ArrayList<RssiItem>();
                mutable_bitField0_ |= 0x00000010;
              }
              items_.add(input.readMessage(RssiItem.PARSER, extensionRegistry));
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              sceneId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FrostEvent.internal_static_com_palmap_rssi_message_RssiInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FrostEvent.internal_static_com_palmap_rssi_message_RssiInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RssiInfo.class, Builder.class);
    }

    public static com.google.protobuf.Parser<RssiInfo> PARSER =
        new com.google.protobuf.AbstractParser<RssiInfo>() {
      public RssiInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RssiInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RssiInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id_data = 1;
    public static final int ID_DATA_FIELD_NUMBER = 1;
    private Object idData_;
    /**
     * <code>required string id_data = 1;</code>
     */
    public boolean hasIdData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id_data = 1;</code>
     */
    public String getIdData() {
      Object ref = idData_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          idData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id_data = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdDataBytes() {
      Object ref = idData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        idData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .com.palmap.rssi.message.IdType id_type = 2;
    public static final int ID_TYPE_FIELD_NUMBER = 2;
    private IdType idType_;
    /**
     * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
     */
    public boolean hasIdType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
     */
    public IdType getIdType() {
      return idType_;
    }

    // required .com.palmap.rssi.message.StubType stub_type = 3;
    public static final int STUB_TYPE_FIELD_NUMBER = 3;
    private StubType stubType_;
    /**
     * <code>required .com.palmap.rssi.message.StubType stub_type = 3;</code>
     */
    public boolean hasStubType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .com.palmap.rssi.message.StubType stub_type = 3;</code>
     */
    public StubType getStubType() {
      return stubType_;
    }

    // required int64 timestamp = 4;
    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // repeated .com.palmap.rssi.message.RssiItem items = 5;
    public static final int ITEMS_FIELD_NUMBER = 5;
    private java.util.List<RssiItem> items_;
    /**
     * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
     */
    public java.util.List<RssiItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
     */
    public java.util.List<? extends RssiItemOrBuilder>
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
     */
    public RssiItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
     */
    public RssiItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    // required int64 scene_id = 6;
    public static final int SCENE_ID_FIELD_NUMBER = 6;
    private long sceneId_;
    /**
     * <code>required int64 scene_id = 6;</code>
     */
    public boolean hasSceneId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 scene_id = 6;</code>
     */
    public long getSceneId() {
      return sceneId_;
    }

    private void initFields() {
      idData_ = "";
      idType_ = IdType.MAC;
      stubType_ = StubType.AP;
      timestamp_ = 0L;
      items_ = java.util.Collections.emptyList();
      sceneId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIdData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStubType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSceneId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdDataBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, idType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, stubType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, timestamp_);
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(5, items_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(6, sceneId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdDataBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, idType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, stubType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, items_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, sceneId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RssiInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RssiInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RssiInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RssiInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RssiInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RssiInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RssiInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RssiInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RssiInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RssiInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RssiInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.palmap.rssi.message.RssiInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RssiInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FrostEvent.internal_static_com_palmap_rssi_message_RssiInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FrostEvent.internal_static_com_palmap_rssi_message_RssiInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RssiInfo.class, Builder.class);
      }

      // Construct using com.palmap.rssi.message.FrostEvent.RssiInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        idData_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        idType_ = IdType.MAC;
        bitField0_ = (bitField0_ & ~0x00000002);
        stubType_ = StubType.AP;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          itemsBuilder_.clear();
        }
        sceneId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FrostEvent.internal_static_com_palmap_rssi_message_RssiInfo_descriptor;
      }

      public RssiInfo getDefaultInstanceForType() {
        return RssiInfo.getDefaultInstance();
      }

      public RssiInfo build() {
        RssiInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RssiInfo buildPartial() {
        RssiInfo result = new RssiInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.idData_ = idData_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.idType_ = idType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stubType_ = stubType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sceneId_ = sceneId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RssiInfo) {
          return mergeFrom((RssiInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RssiInfo other) {
        if (other == RssiInfo.getDefaultInstance()) return this;
        if (other.hasIdData()) {
          bitField0_ |= 0x00000001;
          idData_ = other.idData_;
          onChanged();
        }
        if (other.hasIdType()) {
          setIdType(other.getIdType());
        }
        if (other.hasStubType()) {
          setStubType(other.getStubType());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000010);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        if (other.hasSceneId()) {
          setSceneId(other.getSceneId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIdData()) {
          
          return false;
        }
        if (!hasIdType()) {
          
          return false;
        }
        if (!hasStubType()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasSceneId()) {
          
          return false;
        }
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RssiInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RssiInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id_data = 1;
      private Object idData_ = "";
      /**
       * <code>required string id_data = 1;</code>
       */
      public boolean hasIdData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id_data = 1;</code>
       */
      public String getIdData() {
        Object ref = idData_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          idData_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string id_data = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdDataBytes() {
        Object ref = idData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          idData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id_data = 1;</code>
       */
      public Builder setIdData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        idData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id_data = 1;</code>
       */
      public Builder clearIdData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        idData_ = getDefaultInstance().getIdData();
        onChanged();
        return this;
      }
      /**
       * <code>required string id_data = 1;</code>
       */
      public Builder setIdDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        idData_ = value;
        onChanged();
        return this;
      }

      // required .com.palmap.rssi.message.IdType id_type = 2;
      private IdType idType_ = IdType.MAC;
      /**
       * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
       */
      public boolean hasIdType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
       */
      public IdType getIdType() {
        return idType_;
      }
      /**
       * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
       */
      public Builder setIdType(IdType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        idType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.palmap.rssi.message.IdType id_type = 2;</code>
       */
      public Builder clearIdType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        idType_ = IdType.MAC;
        onChanged();
        return this;
      }

      // required .com.palmap.rssi.message.StubType stub_type = 3;
      private StubType stubType_ = StubType.AP;
      /**
       * <code>required .com.palmap.rssi.message.StubType stub_type = 3;</code>
       */
      public boolean hasStubType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .com.palmap.rssi.message.StubType stub_type = 3;</code>
       */
      public StubType getStubType() {
        return stubType_;
      }
      /**
       * <code>required .com.palmap.rssi.message.StubType stub_type = 3;</code>
       */
      public Builder setStubType(StubType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        stubType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.palmap.rssi.message.StubType stub_type = 3;</code>
       */
      public Builder clearStubType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stubType_ = StubType.AP;
        onChanged();
        return this;
      }

      // required int64 timestamp = 4;
      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // repeated .com.palmap.rssi.message.RssiItem items = 5;
      private java.util.List<RssiItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          items_ = new java.util.ArrayList<RssiItem>(items_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          RssiItem, RssiItem.Builder, RssiItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public java.util.List<RssiItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public RssiItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public Builder setItems(
          int index, RssiItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public Builder setItems(
          int index, RssiItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public Builder addItems(RssiItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public Builder addItems(
          int index, RssiItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public Builder addItems(
          RssiItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public Builder addItems(
          int index, RssiItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public Builder addAllItems(
          Iterable<? extends RssiItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          super.addAll(values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public RssiItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public RssiItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public java.util.List<? extends RssiItemOrBuilder>
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public RssiItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            RssiItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public RssiItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, RssiItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.palmap.rssi.message.RssiItem items = 5;</code>
       */
      public java.util.List<RssiItem.Builder>
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          RssiItem, RssiItem.Builder, RssiItemOrBuilder>
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              RssiItem, RssiItem.Builder, RssiItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // required int64 scene_id = 6;
      private long sceneId_ ;
      /**
       * <code>required int64 scene_id = 6;</code>
       */
      public boolean hasSceneId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 scene_id = 6;</code>
       */
      public long getSceneId() {
        return sceneId_;
      }
      /**
       * <code>required int64 scene_id = 6;</code>
       */
      public Builder setSceneId(long value) {
        bitField0_ |= 0x00000020;
        sceneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 scene_id = 6;</code>
       */
      public Builder clearSceneId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sceneId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.palmap.rssi.message.RssiInfo)
    }

    static {
      defaultInstance = new RssiInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.palmap.rssi.message.RssiInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_palmap_rssi_message_RssiItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_palmap_rssi_message_RssiItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_palmap_rssi_message_RssiInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_palmap_rssi_message_RssiInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020frostEvent.proto\022\027com.palmap.rssi.mess" +
      "age\"[\n\010RssiItem\022\017\n\007id_data\030\001 \002(\t\0220\n\007id_t" +
      "ype\030\002 \002(\0162\037.com.palmap.rssi.message.IdTy" +
      "pe\022\014\n\004rssi\030\003 \002(\005\"\332\001\n\010RssiInfo\022\017\n\007id_data" +
      "\030\001 \002(\t\0220\n\007id_type\030\002 \002(\0162\037.com.palmap.rss" +
      "i.message.IdType\0224\n\tstub_type\030\003 \002(\0162!.co" +
      "m.palmap.rssi.message.StubType\022\021\n\ttimest" +
      "amp\030\004 \002(\003\0220\n\005items\030\005 \003(\0132!.com.palmap.rs" +
      "si.message.RssiItem\022\020\n\010scene_id\030\006 \002(\003*-\n" +
      "\006IdType\022\007\n\003MAC\020\000\022\010\n\004UUID\020\001\022\020\n\014UNKNOWN_TY",
      "PE\020\002*8\n\010StubType\022\006\n\002AP\020\000\022\r\n\tBLUETOOTH\020\001\022" +
      "\025\n\021UNKNOWN_STUB_TYPE\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_palmap_rssi_message_RssiItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_palmap_rssi_message_RssiItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_palmap_rssi_message_RssiItem_descriptor,
              new String[] { "IdData", "IdType", "Rssi", });
          internal_static_com_palmap_rssi_message_RssiInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_palmap_rssi_message_RssiInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_palmap_rssi_message_RssiInfo_descriptor,
              new String[] { "IdData", "IdType", "StubType", "Timestamp", "Items", "SceneId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
