// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopStore.proto

package com.palmap.rssi.message;

public final class ShopStore {
  private ShopStore() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VisitorOrBuilder extends
          // @@protoc_insertion_point(interface_extends:palmapmsg.Visitor)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes phone_mac = 1;</code>
     */
    boolean hasPhoneMac();
    /**
     * <code>optional bytes phone_mac = 1;</code>
     */
    com.google.protobuf.ByteString getPhoneMac();

    /**
     * <code>optional int32 scene_id = 2;</code>
     */
    boolean hasSceneId();
    /**
     * <code>optional int32 scene_id = 2;</code>
     */
    int getSceneId();

    /**
     * <code>optional bytes phone_brand = 3;</code>
     */
    boolean hasPhoneBrand();
    /**
     * <code>optional bytes phone_brand = 3;</code>
     */
    com.google.protobuf.ByteString getPhoneBrand();

    /**
     * <code>optional uint64 time_stamp = 4;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>optional uint64 time_stamp = 4;</code>
     */
    long getTimeStamp();

    /**
     * <code>optional bool isCustomer = 5;</code>
     */
    boolean hasIsCustomer();
    /**
     * <code>optional bool isCustomer = 5;</code>
     */
    boolean getIsCustomer();

    /**
     * <code>repeated sint32 rssi = 6;</code>
     */
    java.util.List<java.lang.Integer> getRssiList();
    /**
     * <code>repeated sint32 rssi = 6;</code>
     */
    int getRssiCount();
    /**
     * <code>repeated sint32 rssi = 6;</code>
     */
    int getRssi(int index);
  }
  /**
   * Protobuf type {@code palmapmsg.Visitor}
   */
  public static final class Visitor extends
          com.google.protobuf.GeneratedMessage implements
          // @@protoc_insertion_point(message_implements:palmapmsg.Visitor)
          VisitorOrBuilder {
    // Use Visitor.newBuilder() to construct.
    private Visitor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Visitor(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Visitor defaultInstance;
    public static Visitor getDefaultInstance() {
      return defaultInstance;
    }

    public Visitor getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Visitor(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              phoneMac_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sceneId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              phoneBrand_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timeStamp_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isCustomer_ = input.readBool();
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                rssi_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              rssi_.add(input.readSInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                rssi_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                rssi_.add(input.readSInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          rssi_ = java.util.Collections.unmodifiableList(rssi_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.palmap.rssi.message.ShopStore.internal_static_palmapmsg_Visitor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.palmap.rssi.message.ShopStore.internal_static_palmapmsg_Visitor_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.palmap.rssi.message.ShopStore.Visitor.class, com.palmap.rssi.message.ShopStore.Visitor.Builder.class);
    }

    public static com.google.protobuf.Parser<Visitor> PARSER =
            new com.google.protobuf.AbstractParser<Visitor>() {
              public Visitor parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new Visitor(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<Visitor> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PHONE_MAC_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString phoneMac_;
    /**
     * <code>optional bytes phone_mac = 1;</code>
     */
    public boolean hasPhoneMac() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes phone_mac = 1;</code>
     */
    public com.google.protobuf.ByteString getPhoneMac() {
      return phoneMac_;
    }

    public static final int SCENE_ID_FIELD_NUMBER = 2;
    private int sceneId_;
    /**
     * <code>optional int32 scene_id = 2;</code>
     */
    public boolean hasSceneId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 scene_id = 2;</code>
     */
    public int getSceneId() {
      return sceneId_;
    }

    public static final int PHONE_BRAND_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString phoneBrand_;
    /**
     * <code>optional bytes phone_brand = 3;</code>
     */
    public boolean hasPhoneBrand() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes phone_brand = 3;</code>
     */
    public com.google.protobuf.ByteString getPhoneBrand() {
      return phoneBrand_;
    }

    public static final int TIME_STAMP_FIELD_NUMBER = 4;
    private long timeStamp_;
    /**
     * <code>optional uint64 time_stamp = 4;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 time_stamp = 4;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int ISCUSTOMER_FIELD_NUMBER = 5;
    private boolean isCustomer_;
    /**
     * <code>optional bool isCustomer = 5;</code>
     */
    public boolean hasIsCustomer() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool isCustomer = 5;</code>
     */
    public boolean getIsCustomer() {
      return isCustomer_;
    }

    public static final int RSSI_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Integer> rssi_;
    /**
     * <code>repeated sint32 rssi = 6;</code>
     */
    public java.util.List<java.lang.Integer>
    getRssiList() {
      return rssi_;
    }
    /**
     * <code>repeated sint32 rssi = 6;</code>
     */
    public int getRssiCount() {
      return rssi_.size();
    }
    /**
     * <code>repeated sint32 rssi = 6;</code>
     */
    public int getRssi(int index) {
      return rssi_.get(index);
    }

    private void initFields() {
      phoneMac_ = com.google.protobuf.ByteString.EMPTY;
      sceneId_ = 0;
      phoneBrand_ = com.google.protobuf.ByteString.EMPTY;
      timeStamp_ = 0L;
      isCustomer_ = false;
      rssi_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, phoneMac_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sceneId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, phoneBrand_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, timeStamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, isCustomer_);
      }
      for (int i = 0; i < rssi_.size(); i++) {
        output.writeSInt32(6, rssi_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(1, phoneMac_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(2, sceneId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(3, phoneBrand_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(4, timeStamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBoolSize(5, isCustomer_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < rssi_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
                  .computeSInt32SizeNoTag(rssi_.get(i));
        }
        size += dataSize;
        size += 1 * getRssiList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.palmap.rssi.message.ShopStore.Visitor parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.palmap.rssi.message.ShopStore.Visitor parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.palmap.rssi.message.ShopStore.Visitor parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.palmap.rssi.message.ShopStore.Visitor parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.palmap.rssi.message.ShopStore.Visitor parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.palmap.rssi.message.ShopStore.Visitor parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.palmap.rssi.message.ShopStore.Visitor parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.palmap.rssi.message.ShopStore.Visitor parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.palmap.rssi.message.ShopStore.Visitor parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.palmap.rssi.message.ShopStore.Visitor parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.palmap.rssi.message.ShopStore.Visitor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code palmapmsg.Visitor}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:palmapmsg.Visitor)
            com.palmap.rssi.message.ShopStore.VisitorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.palmap.rssi.message.ShopStore.internal_static_palmapmsg_Visitor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.palmap.rssi.message.ShopStore.internal_static_palmapmsg_Visitor_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.palmap.rssi.message.ShopStore.Visitor.class, com.palmap.rssi.message.ShopStore.Visitor.Builder.class);
      }

      // Construct using com.palmap.rssi.message.ShopStore.Visitor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        phoneMac_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        sceneId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        phoneBrand_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        isCustomer_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        rssi_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.palmap.rssi.message.ShopStore.internal_static_palmapmsg_Visitor_descriptor;
      }

      public com.palmap.rssi.message.ShopStore.Visitor getDefaultInstanceForType() {
        return com.palmap.rssi.message.ShopStore.Visitor.getDefaultInstance();
      }

      public com.palmap.rssi.message.ShopStore.Visitor build() {
        com.palmap.rssi.message.ShopStore.Visitor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.palmap.rssi.message.ShopStore.Visitor buildPartial() {
        com.palmap.rssi.message.ShopStore.Visitor result = new com.palmap.rssi.message.ShopStore.Visitor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.phoneMac_ = phoneMac_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sceneId_ = sceneId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.phoneBrand_ = phoneBrand_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isCustomer_ = isCustomer_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          rssi_ = java.util.Collections.unmodifiableList(rssi_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.rssi_ = rssi_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.palmap.rssi.message.ShopStore.Visitor) {
          return mergeFrom((com.palmap.rssi.message.ShopStore.Visitor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.palmap.rssi.message.ShopStore.Visitor other) {
        if (other == com.palmap.rssi.message.ShopStore.Visitor.getDefaultInstance()) return this;
        if (other.hasPhoneMac()) {
          setPhoneMac(other.getPhoneMac());
        }
        if (other.hasSceneId()) {
          setSceneId(other.getSceneId());
        }
        if (other.hasPhoneBrand()) {
          setPhoneBrand(other.getPhoneBrand());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasIsCustomer()) {
          setIsCustomer(other.getIsCustomer());
        }
        if (!other.rssi_.isEmpty()) {
          if (rssi_.isEmpty()) {
            rssi_ = other.rssi_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureRssiIsMutable();
            rssi_.addAll(other.rssi_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.palmap.rssi.message.ShopStore.Visitor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.palmap.rssi.message.ShopStore.Visitor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString phoneMac_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes phone_mac = 1;</code>
       */
      public boolean hasPhoneMac() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes phone_mac = 1;</code>
       */
      public com.google.protobuf.ByteString getPhoneMac() {
        return phoneMac_;
      }
      /**
       * <code>optional bytes phone_mac = 1;</code>
       */
      public Builder setPhoneMac(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        phoneMac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes phone_mac = 1;</code>
       */
      public Builder clearPhoneMac() {
        bitField0_ = (bitField0_ & ~0x00000001);
        phoneMac_ = getDefaultInstance().getPhoneMac();
        onChanged();
        return this;
      }

      private int sceneId_ ;
      /**
       * <code>optional int32 scene_id = 2;</code>
       */
      public boolean hasSceneId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 scene_id = 2;</code>
       */
      public int getSceneId() {
        return sceneId_;
      }
      /**
       * <code>optional int32 scene_id = 2;</code>
       */
      public Builder setSceneId(int value) {
        bitField0_ |= 0x00000002;
        sceneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 scene_id = 2;</code>
       */
      public Builder clearSceneId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sceneId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString phoneBrand_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes phone_brand = 3;</code>
       */
      public boolean hasPhoneBrand() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes phone_brand = 3;</code>
       */
      public com.google.protobuf.ByteString getPhoneBrand() {
        return phoneBrand_;
      }
      /**
       * <code>optional bytes phone_brand = 3;</code>
       */
      public Builder setPhoneBrand(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        phoneBrand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes phone_brand = 3;</code>
       */
      public Builder clearPhoneBrand() {
        bitField0_ = (bitField0_ & ~0x00000004);
        phoneBrand_ = getDefaultInstance().getPhoneBrand();
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <code>optional uint64 time_stamp = 4;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 time_stamp = 4;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>optional uint64 time_stamp = 4;</code>
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000008;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 time_stamp = 4;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private boolean isCustomer_ ;
      /**
       * <code>optional bool isCustomer = 5;</code>
       */
      public boolean hasIsCustomer() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool isCustomer = 5;</code>
       */
      public boolean getIsCustomer() {
        return isCustomer_;
      }
      /**
       * <code>optional bool isCustomer = 5;</code>
       */
      public Builder setIsCustomer(boolean value) {
        bitField0_ |= 0x00000010;
        isCustomer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isCustomer = 5;</code>
       */
      public Builder clearIsCustomer() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isCustomer_ = false;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> rssi_ = java.util.Collections.emptyList();
      private void ensureRssiIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          rssi_ = new java.util.ArrayList<java.lang.Integer>(rssi_);
          bitField0_ |= 0x00000020;
        }
      }
      /**
       * <code>repeated sint32 rssi = 6;</code>
       */
      public java.util.List<java.lang.Integer>
      getRssiList() {
        return java.util.Collections.unmodifiableList(rssi_);
      }
      /**
       * <code>repeated sint32 rssi = 6;</code>
       */
      public int getRssiCount() {
        return rssi_.size();
      }
      /**
       * <code>repeated sint32 rssi = 6;</code>
       */
      public int getRssi(int index) {
        return rssi_.get(index);
      }
      /**
       * <code>repeated sint32 rssi = 6;</code>
       */
      public Builder setRssi(
              int index, int value) {
        ensureRssiIsMutable();
        rssi_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 rssi = 6;</code>
       */
      public Builder addRssi(int value) {
        ensureRssiIsMutable();
        rssi_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 rssi = 6;</code>
       */
      public Builder addAllRssi(
              java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureRssiIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, rssi_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 rssi = 6;</code>
       */
      public Builder clearRssi() {
        rssi_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:palmapmsg.Visitor)
    }

    static {
      defaultInstance = new Visitor(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:palmapmsg.Visitor)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_palmapmsg_Visitor_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_palmapmsg_Visitor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\017shopStore.proto\022\tpalmapmsg\"y\n\007Visitor\022" +
                    "\021\n\tphone_mac\030\001 \001(\014\022\020\n\010scene_id\030\002 \001(\005\022\023\n\013" +
                    "phone_brand\030\003 \001(\014\022\022\n\ntime_stamp\030\004 \001(\004\022\022\n" +
                    "\nisCustomer\030\005 \001(\010\022\014\n\004rssi\030\006 \003(\021B\031\n\027com.p" +
                    "almap.rssi.message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_palmapmsg_Visitor_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_palmapmsg_Visitor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_palmapmsg_Visitor_descriptor,
            new java.lang.String[] { "PhoneMac", "SceneId", "PhoneBrand", "TimeStamp", "IsCustomer", "Rssi", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
